"""description: nick&avatar4

Revision ID: 598fbd2e54f5
Revises: 6e0f375ff121
Create Date: 2020-08-14 13:48:18.781547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598fbd2e54f5'
down_revision = '6e0f375ff121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ftusers', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.add_column('ftusers', sa.Column('nick', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ftusers', 'nick')
    op.drop_column('ftusers', 'avatar')
    # ### end Alembic commands ###
