"""description: nick&avatar3

Revision ID: 6e0f375ff121
Revises: c9816643b01a
Create Date: 2020-08-14 13:47:03.442728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0f375ff121'
down_revision = 'c9816643b01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
